### ISSUE TITLE
How to remove specific entries

### ISSUE THREAD

**Issue by MFaisalZaki** [microsoft/sarif-tools#13]
I tried to `copy` while applying `blame-filter`, but it didn't work as expected. 

I want to ask if it is possible to provide a specific entry with `filename` and `lines` to be filtered out.

**Comment by balgillo** [comment]
Hi, sorry for the delay spotting the issue that you have raised.  Thank you for your interest in sarif-tools!

I checked the `copy` operation with blame-filter and it worked as I expect, i.e. it filters issues by author information as described in the [README](https://github.com/microsoft/sarif-tools/blob/e803a8863fd281b4886caa384c5f4efe1d291a06/README.md#blame-filtering).  The tool doesn't have a facility for filtering issues by filename or line location.  Is that a feature that you want - can you elaborate on your needs?
