### ISSUE TITLE
sarif codeclimate : invalid choice

### ISSUE THREAD

**Issue by sinkcup** [microsoft/sarif-tools#29]
<img width="1147" alt="image" src="https://github.com/microsoft/sarif-tools/assets/4971414/586861cc-87fb-465b-9e76-902d9ba606aa">

## reason

the new code is in master, not in git tag.

<img width="1148" alt="image" src="https://github.com/microsoft/sarif-tools/assets/4971414/edb7455a-733e-4e3a-aceb-51601a0a4e4e">

<img width="426" alt="image" src="https://github.com/microsoft/sarif-tools/assets/4971414/24ffcc21-e99f-40f3-b6e1-3ae99c01c19f">

## possible fix

create a new git tag

**Comment by balgillo** [comment]
Hi, we are working on the new release.  It should be released in the next month.

**Comment by balgillo** [comment]
v2.0.0 is now on PyPI, including the `sarif codeclimate` command :-)
