### ISSUE TITLE
Support for `none` as a SARIF severity level

### ISSUE THREAD

**Issue by venkat-raman-wday** [microsoft/sarif-tools#47]
Hello, [3.27.10](https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127839) allows for `none` as a valid severity level. However, [sarif_file.py:16](https://github.com/microsoft/sarif-tools/blob/main/sarif/sarif_file.py#L16) supports only the three "main" severities. Can we request support "none" as well.
The SARIF Viewer extension for VS Code does support `none` as a valid severity level. But the sarif-tools library doesn't produce a record for findings count by "none" although `get_records()` does produce it correctly. Thanks!

**Comment by balgillo** [comment]
Thanks for pointing this out... we will work on this change.

**Comment by balgillo** [comment]
`none` severity level is now supported in v3.0.1 which is now on PyPI.
